ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION SQRT__AS,G__EXP__2,CONJG__CKM1X1,CONJG__CKM3X3
     $ ,CKM3X3,MZ__EXP__2,MZ__EXP__4,SQRT__2,MH__EXP__2,AEW,SQRT__AEW
     $ ,EE,MW__EXP__2,SW2,CW,SQRT__SW2,SW,G1,GW,VEV,VEV__EXP__2,LAM,YB
     $ ,YT,YTAU,MUH,EE__EXP__2,SW__EXP__2,CW__EXP__2,AEWM1,GF,AS,YMB
     $ ,YMT,YMTAU

      COMMON/PARAMS_R/ SQRT__AS,G__EXP__2,CONJG__CKM1X1,CONJG__CKM3X3
     $ ,CKM3X3,MZ__EXP__2,MZ__EXP__4,SQRT__2,MH__EXP__2,AEW,SQRT__AEW
     $ ,EE,MW__EXP__2,SW2,CW,SQRT__SW2,SW,G1,GW,VEV,VEV__EXP__2,LAM,YB
     $ ,YT,YTAU,MUH,EE__EXP__2,SW__EXP__2,CW__EXP__2,AEWM1,GF,AS,YMB
     $ ,YMT,YMTAU


      DOUBLE COMPLEX COMPLEXI,I1X33,I2X33,I3X33,I4X33

      COMMON/PARAMS_C/ COMPLEXI,I1X33,I2X33,I3X33,I4X33


